# Generated by Django 5.1.3 on 2024-12-02 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cant_votos', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('comentario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='hoteles.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Atributo_Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_atributo', models.CharField(max_length=255)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos_hoteles', to='hoteles.atributo')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='hoteles.hotel')),
            ],
        ),
    ]
